### PR TITLE
Fix shutdown of mysql

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Don't merge yet, needs to be tested a bit more

**Comment by aptalca** [comment]
Thanks, fixed the linting

**Comment by aptalca** [comment]
Tested it on production servers and it is ready to merge

**Comment by aptalca** [comment]
Either way works: http://linuxcommand.org/lc3_man_pages/kill1.html

**Comment by tobbenb** [comment]
Ah.... Me not reading good enough... I'll approve it once I'm on a desktop.

**Pull request merged**
