### PR TITLE
Master alpine

### PR DESCRIPTION
**Pull request by nemchik**
Merge alpine branch/tag into master/latest.

### CODE REVIEW

**Review by drizuid — APPROVED** [review]

**Review by Roxedus — APPROVED** [review]

**Comment by TheSpad** [comment]
Related PR https://github.com/linuxserver/cstate/pull/37

**Comment by thezoggy** [comment]
Since this change I've had mariadb randomly stopped accepting connections until docker is restarted. Is there anything specific I should look at on why this issue has started with this docker?

**Comment by Roxedus** [comment]
MariaDB was probably not shut down fully before the update, we have seen it needs a bit of time to gracefully shutdown. Pre-migration this wasn't a problem, as it would kindly restore it.

**Comment by thezoggy** [comment]
> MariaDB was probably not shut down fully before the update, we have seen it needs a bit of time to gracefully shutdown. Pre-migration this wasn't a problem, as it would kindly restore it. 

I'm using this on unraid 6.8.. is there some option or setting I need to modify to make it play nice or some manual action I need to do to make it happier? I thought at first it was just a one time quirk of the update but here it is less than 24h and it's happening again.

**Comment by thezoggy** [comment]
sample of my kodi logs showing when i run into the issue:
```
2021-09-01 09:58:50.454 T:24263    INFO <general>: Starting Kodi (19.1 (19.1.0) Git:20210508-85e05228b4). Platform: Android ARM 64-bit
...
2021-09-01 09:58:50.504 T:24263    INFO <general>: Contents of special://profile/advancedsettings.xml are...
                                                   <advancedsettings>
                                                     <loglevel>0</loglevel>
                                                     <videodatabase>
                                                       <type>mysql</type>
                                                       <host>192.168.0.11</host>
                                                       <port>3306</port>
...
2021-09-01 09:58:53.110 T:24291    INFO <general>: MYSQL: Connected to version 10.5.12-MariaDB-log
2021-09-01 09:58:53.115 T:24291    INFO <general>: Running database version MyMusic82
2021-09-01 09:58:53.121 T:24291    INFO <general>: Running database version MyVideos119
...
2021-09-01 09:58:53.555 T:24263    INFO <general>: JSONRPC v12.3.0: Successfully initialized
2021-09-01 09:58:53.574 T:24292   ERROR <general>: SQL: [MyVideos119] An unknown error occurred
                                                   Query: SELECT * FROM streamdetails WHERE idFile = 16300

2021-09-01 09:58:53.655 T:24292   ERROR <general>: GetStreamDetails(16300) failed
...
2021-09-01 09:58:53.836 T:24291   ERROR <general>: GetArtForItem(1125) failed
2021-09-01 09:58:53.836 T:24291   ERROR <general>: SQL: Missing result set!
2021-09-01 09:58:53.836 T:24291   ERROR <general>: GetArtForItem(181) failed
2021-09-01 09:58:53.841 T:24291   ERROR <general>: SQL: [MyVideos119] Commands were executed in an improper order
                                                   Query: SELECT * FROM streamdetails WHERE idFile = 733
```


looking around, i found few different things saying that it may just be mariadb 10.5 itself
found this, https://discourse.coreelec.org/t/the-state-of-mariadb-in-the-context-of-coreelec/13025

going to try that out, updating custom.cnf 
```
[mysqld]
innodb_compression_default=OFF
```

**Comment by thezoggy** [comment]
looking on forums, looks like the recommended fix is just to downgrade back to `version-110.4.21mariabionic`  :/

**Comment by TheSpad** [comment]
You don't need a backup, you can just downgrade to the older tag and then upgrade cleanly.

**Comment by thezoggy** [comment]
> 
> 
> You don't need a backup, you can just downgrade to the older tag and then upgrade cleanly.

I tried to use the older tag but on docker startup it just kept crashing/restarting


```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 90-warning: executing...

******************************************************
******************************************************
* *
* *
* This image will soon be rebased *
* from ubuntu to alpine. *
* Please be aware, this may cause issues *
* It is strongly recommended to make backups *
* of your config and databases before *
* updating your image to the alpine base. *
* *
* *
******************************************************
******************************************************
[cont-init.d] 90-warning: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
210901 11:49:22 mysqld_safe Logging to syslog.
210901 11:49:22 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:23 mysqld_safe Logging to syslog.
210901 11:49:23 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:24 mysqld_safe Logging to syslog.
210901 11:49:24 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:25 mysqld_safe Logging to syslog.
210901 11:49:25 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:26 mysqld_safe Logging to syslog.
210901 11:49:26 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:27 mysqld_safe Logging to syslog.
210901 11:49:27 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:27 mysqld_safe Logging to syslog.
210901 11:49:27 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:28 mysqld_safe Logging to syslog.
210901 11:49:28 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:29 mysqld_safe Logging to syslog.
210901 11:49:29 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:29 mysqld_safe Logging to syslog.
210901 11:49:29 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:30 mysqld_safe Logging to syslog.
210901 11:49:30 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:31 mysqld_safe Logging to syslog.
210901 11:49:31 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:31 mysqld_safe Logging to syslog.
210901 11:49:31 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:32 mysqld_safe Logging to syslog.
210901 11:49:32 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:33 mysqld_safe Logging to syslog.
210901 11:49:33 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:33 mysqld_safe Logging to syslog.
210901 11:49:33 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:34 mysqld_safe Logging to syslog.
210901 11:49:34 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:35 mysqld_safe Logging to syslog.
210901 11:49:35 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:36 mysqld_safe Logging to syslog.
210901 11:49:36 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:37 mysqld_safe Logging to syslog.
210901 11:49:37 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:38 mysqld_safe Logging to syslog.
210901 11:49:38 mysqld_safe Starting mysqld daemon with databases from /config/databases
210901 11:49:39 mysqld_safe Logging to syslog.
```

**Comment by TheSpad** [comment]
Looks like the original DB may be corrupted, possibly as a result of not being shut down cleanly. Unfortunately if you don't have a backup there's no a lot that can be done - it's one of the reasons we advise against auto-updating.

**Comment by thezoggy** [comment]
I got it working on old tag finally. Ran mysql_upgrade and then removed aria and ib log file

**Pull request merged**
