### PR TITLE
Rebase to alpine. Add mariadb-backup.

### PR DESCRIPTION
**Pull request by nemchik**
Depends on https://github.com/linuxserver/docker-jenkins-builder/pull/93 and then https://github.com/linuxserver/docker-jenkins-builder/pull/90

### CODE REVIEW

**Comment by nemchik** [comment]
Thanks to @hydazz this should now be ready for review/merge (once jenkins reports).

**Comment by hydazz** [comment]
Just realised I forgot to update my pr to fix this - the pid file location should me moved from the  `mariadb-server.cnf` File to the `mysqld_safe` run command. On every container restart `pid-file=/var/run/mysqld/mysqld.pid` is echoed into `mariadb-server.cnf` and it can get messy. See [here](https://github.com/hydazz/docker-mariadb/blob/main/root/etc/cont-init.d/20-config) and [here](https://github.com/hydazz/docker-mariadb/blob/main/root/etc/services.d/mariadb/run) for the updated files, a very little so I don’t think it’s worth opening another pr over.

**Comment by nemchik** [comment]
> Just realised I forgot to update my pr to fix this - the pid file location should me moved from the `mariadb-server.cnf` File to the `mysqld_safe` run command. On every container restart `pid-file=/var/run/mysqld/mysqld.pid` is echoed into `mariadb-server.cnf` and it can get messy. See [here](https://github.com/hydazz/docker-mariadb/blob/main/root/etc/cont-init.d/20-config) and [here](https://github.com/hydazz/docker-mariadb/blob/main/root/etc/services.d/mariadb/run) for the updated files, a very little so I don’t think it’s worth opening another pr over.

Good call. Fixing here now.

**Comment by nemchik** [comment]
f7f5e7209a5b0a947d580656efab54edebc821fa relies on https://github.com/linuxserver/docker-jenkins-builder/pull/93 which passes the correct version arg for MARIADB_VERSION. The current behavior passes a hash, but the hash does not seem to be correct. The new behavior passes the package version from APKINDEX.

We can still use the image from https://ci-tests.linuxserver.io/lspipepr/mariadb/b2856f90-pkg-601efecc-pr-66/index.html to test and confirm the changes to this image are correct and do not cause issues. Once https://github.com/linuxserver/docker-jenkins-builder/pull/93 is merged we can re-trigger builds on f7f5e7209a5b0a947d580656efab54edebc821fa and confirm the build succeeds.

**Review by Bolkarr — APPROVED** [review]

**Comment by nemchik** [comment]
For those interested, the plan with this image is to rebase and squash the commits so the git history isn't so large, and then to set this up to be an independent branch released as the `alpine` tag. We will transition the `master` branch and `latest` tag to using alpine after providing appropriate heads up.

**Comment by Bolkarr** [comment]
Thanks, 
Since couple systems require newer mariadb version, many of us are interested in this hoping the mariadb version for armhf (v7) would be upgraded to 10.2+ (I see 10.5+ in the files?)

**Comment by Roxedus** [comment]
As it stands right now it would give `10.5.8` as you can see [here](https://pkgs.alpinelinux.org/package/v3.13/main/armhf/mariadb)

**Comment by nemchik** [comment]
I'm closing this PR and will be deleting the alpine branch. A new alpine branch will be made to release the alpine tag for the image.

**Comment by nemchik** [comment]
This is replaced with https://github.com/linuxserver/docker-mariadb/pull/72 which will release the `alpine` tag for this image until the alpine rebase is ready to be released as `latest`.

**Pull request closed without merging**
